### PR TITLE
Lap to

### PR DESCRIPTION
**Pull request by lapto123**
Exercise Chapter 3, create new intent activity and pass parameter to new activity. Open new activity with a click on button. New feature branch "LapTo" for this change.

### CODE REVIEW

**Comment by lapto123** [comment]
updated DisplayActivity.class file.

**Comment by lapto123** [comment]
modified layouts files.

**Comment by Cascadia-DebraWard** [comment]
Please show me how you did this.

**Comment by lapto123** [comment]
I would love to help you tomorrow. but if you want to try out ahead, hope this will help.
1. from Brian Repo, click on "Fork" locate upper right.
https://github.com/MobileApps-Cascadia/chapter-03
2. you should see chapter-03 in your own Repo3. Clone it to your desktop GitHub4. open it from Android Studio5. Create new branch or make a Revision from Master branch. do this in android studio right click on App, Git + Repository + Branches, then Create new Branch or Make new Revision from Master.6. Make any change you want, code or layout whatever7. Committed and Push to your Repo8. Pull Requested the Brian Repo, which what you saw mind.

that all,lap
 


     On Tuesday, April 21, 2015 8:16 PM, Debra Ward <notifications@github.com> wrote:
   
 

 Please show me how you did this.—

**Comment by lapto123** [comment]
1. from Brian Repo, click on "Fork" locate upper right.
   https://github.com/MobileApps-Cascadia/chapter-03
2. you should see chapter-03 in your own Repo
3. Clone it to your desktop GitHub
4. open it from Android Studio
5. Create new branch or make a Revision from Master branch. do this in android studio right click on App, Git + Repository + Branches, then Create new Branch or Make new Revision from Master.
6. Make any change you want, code or layout whatever
7. Committed and Push to your Repo
8. Pull Requested to Brian Repo, which what you saw mind.

that all,
lap

**Comment by Bansenauer-Cascadia** [comment]
Well done

**Pull request closed without merging**
